/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanyProfile {
  'logoBase64' : string,
  'gstNumber' : string,
  'address' : string,
  'contactEmail' : string,
  'contactPhone' : string,
}
export interface Customer {
  'storeNumber' : string,
  'gstNumber' : [] | [string],
  'password' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'companyName' : string,
  'phone' : string,
}
export interface Order {
  'status' : string,
  'paymentMethod' : string,
  'storeNumber' : string,
  'gstNumber' : [] | [string],
  'deleteReason' : [] | [string],
  'orderId' : string,
  'invoiceNumber' : [] | [string],
  'deliverySignature' : [] | [string],
  'totalAmount' : number,
  'address' : string,
  'timestamp' : Time,
  'companyName' : string,
  'items' : Array<OrderItem>,
  'poNumber' : string,
}
export interface OrderItem {
  'qty' : bigint,
  'rate' : number,
  'unit' : string,
  'productId' : bigint,
  'productName' : string,
}
export interface Payment {
  'deleted' : boolean,
  'paymentMethod' : string,
  'paymentAdviceImage' : string,
  'storeNumber' : string,
  'deleteReason' : [] | [string],
  'utrDetails' : [] | [string],
  'paymentId' : string,
  'timestamp' : Time,
  'companyName' : string,
  'amount' : number,
  'chequeDetails' : [] | [string],
}
export interface Product {
  'id' : bigint,
  'active' : boolean,
  'name' : string,
  'rate' : number,
  'unit' : string,
  'imageBase64' : string,
}
export interface ProductInput {
  'name' : string,
  'rate' : number,
  'unit' : string,
  'imageBase64' : [] | [string],
}
export interface RiderAssignment {
  'orderId' : string,
  'riderEmail' : string,
  'riderPhone' : string,
  'riderName' : string,
}
export interface RiderProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface StatementEntry {
  'entryDate' : Time,
  'entryType' : string,
  'referenceNumber' : string,
  'storeNumber' : string,
  'credit' : number,
  'companyName' : string,
  'debit' : number,
}
export interface SubUser {
  'roleText' : string,
  'active' : boolean,
  'password' : string,
  'email' : string,
}
export type Time = bigint;
export type UserRole = { 'manager' : null } |
  { 'admin' : null } |
  { 'accounts' : null };
export interface _SERVICE {
  'addCustomer' : ActorMethod<[string, Customer], undefined>,
  'addPayment' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      string,
      [] | [string],
      [] | [string],
      string,
    ],
    undefined
  >,
  'adminLogin' : ActorMethod<[string, string], string>,
  'assignRider' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'changeAdminPassword' : ActorMethod<[string, string], undefined>,
  'changeSubUserPassword' : ActorMethod<[string, string, string], undefined>,
  'createSubUser' : ActorMethod<[string, string, UserRole], undefined>,
  'createSubUserWithPassword' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'customerLogin' : ActorMethod<[string, string], string>,
  'deleteCustomer' : ActorMethod<[string, string], undefined>,
  'deleteOrder' : ActorMethod<[string, string, string], undefined>,
  'deletePayment' : ActorMethod<[string, string, string], undefined>,
  'editOrderItems' : ActorMethod<[string, string, Array<OrderItem>], undefined>,
  'editPayment' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      string,
      [] | [string],
      [] | [string],
      string,
    ],
    undefined
  >,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAdminRole' : ActorMethod<[string], string>,
  'getAdminStatus' : ActorMethod<[string], boolean>,
  'getAllCustomerOrders' : ActorMethod<[string], Array<Order>>,
  'getAllCustomerPayments' : ActorMethod<[string], Array<Payment>>,
  'getAllCustomers' : ActorMethod<[string], Array<Customer>>,
  'getAllOrders' : ActorMethod<[string], Array<Order>>,
  'getAllPayments' : ActorMethod<[string], Array<Payment>>,
  'getAllProducts' : ActorMethod<[string], Array<Product>>,
  'getAllRiderAssignments' : ActorMethod<[string], Array<RiderAssignment>>,
  'getAllRiderProfiles' : ActorMethod<[string], Array<RiderProfile>>,
  'getAllSubUsers' : ActorMethod<[string], Array<SubUser>>,
  'getCompanyProfile' : ActorMethod<[], CompanyProfile>,
  'getCompanyStatement' : ActorMethod<
    [string, bigint, bigint],
    Array<StatementEntry>
  >,
  'getCustomer' : ActorMethod<
    [string],
    [] | [
      {
        'storeNumber' : string,
        'gstNumber' : [] | [string],
        'address' : string,
        'companyName' : string,
      }
    ]
  >,
  'getCustomerStatement' : ActorMethod<
    [string, string, bigint, bigint],
    Array<StatementEntry>
  >,
  'getMyStatement' : ActorMethod<
    [string, bigint, bigint],
    Array<StatementEntry>
  >,
  'getOrdersByStore' : ActorMethod<[string, string], Array<Order>>,
  'getOrdersForRider' : ActorMethod<[string, string], Array<Order>>,
  'getPaymentsByStore' : ActorMethod<[string, string], Array<Payment>>,
  'getRiderAssignment' : ActorMethod<[string, string], [] | [RiderAssignment]>,
  'getRiderProfile' : ActorMethod<[string, string], [] | [RiderProfile]>,
  'getWebhookUrl' : ActorMethod<[string], string>,
  'markOrderDeliveredWithSignature' : ActorMethod<
    [string, string, string],
    undefined
  >,
  'placeOrder' : ActorMethod<
    [string, string, string, string, Array<OrderItem>],
    string
  >,
  'placeOrderV2' : ActorMethod<
    [string, string, string, string, [] | [string], Array<OrderItem>, string],
    string
  >,
  'replaceCustomers' : ActorMethod<[string, Array<Customer>], undefined>,
  'replaceProducts' : ActorMethod<[string, Array<string>], undefined>,
  'replaceProductsWithDetails' : ActorMethod<
    [string, Array<ProductInput>],
    undefined
  >,
  'saveRiderProfile' : ActorMethod<[string, string, string, string], undefined>,
  'setCompanyProfile' : ActorMethod<[string, CompanyProfile], undefined>,
  'setWebhookUrl' : ActorMethod<[string, string], undefined>,
  'subUserLogin' : ActorMethod<[string, string], string>,
  'subUserLoginV2' : ActorMethod<[string, string], string>,
  'toggleProduct' : ActorMethod<[string, bigint], undefined>,
  'toggleSubUser' : ActorMethod<[string, string], undefined>,
  'updateCustomer' : ActorMethod<[string, string, Customer], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string, string], undefined>,
  'updateOrderStatusRider' : ActorMethod<[string, string, string], undefined>,
  'updateProductImage' : ActorMethod<[string, bigint, string], undefined>,
  'updateProductRate' : ActorMethod<[string, bigint, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];