/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Customer = IDL.Record({
  'storeNumber' : IDL.Text,
  'gstNumber' : IDL.Opt(IDL.Text),
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'accounts' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'rate' : IDL.Float64,
  'unit' : IDL.Text,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'rate' : IDL.Float64,
  'unit' : IDL.Text,
  'imageBase64' : IDL.Text,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'storeNumber' : IDL.Text,
  'gstNumber' : IDL.Opt(IDL.Text),
  'deleteReason' : IDL.Opt(IDL.Text),
  'orderId' : IDL.Text,
  'invoiceNumber' : IDL.Opt(IDL.Text),
  'deliverySignature' : IDL.Opt(IDL.Text),
  'totalAmount' : IDL.Float64,
  'address' : IDL.Text,
  'timestamp' : Time,
  'companyName' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'poNumber' : IDL.Text,
});
export const Payment = IDL.Record({
  'deleted' : IDL.Bool,
  'paymentMethod' : IDL.Text,
  'paymentAdviceImage' : IDL.Text,
  'storeNumber' : IDL.Text,
  'deleteReason' : IDL.Opt(IDL.Text),
  'utrDetails' : IDL.Opt(IDL.Text),
  'paymentId' : IDL.Text,
  'timestamp' : Time,
  'companyName' : IDL.Text,
  'amount' : IDL.Float64,
  'chequeDetails' : IDL.Opt(IDL.Text),
});
export const RiderAssignment = IDL.Record({
  'orderId' : IDL.Text,
  'riderEmail' : IDL.Text,
  'riderPhone' : IDL.Text,
  'riderName' : IDL.Text,
});
export const RiderProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubUser = IDL.Record({
  'roleText' : IDL.Text,
  'active' : IDL.Bool,
  'password' : IDL.Text,
  'email' : IDL.Text,
});
export const CompanyProfile = IDL.Record({
  'logoBase64' : IDL.Text,
  'gstNumber' : IDL.Text,
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const StatementEntry = IDL.Record({
  'entryDate' : Time,
  'entryType' : IDL.Text,
  'referenceNumber' : IDL.Text,
  'storeNumber' : IDL.Text,
  'credit' : IDL.Float64,
  'companyName' : IDL.Text,
  'debit' : IDL.Float64,
});
export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'rate' : IDL.Float64,
  'unit' : IDL.Text,
  'imageBase64' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([IDL.Text, Customer], [], []),
  'addPayment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'assignRider' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'changeSubUserPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createSubUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  'createSubUserWithPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'customerLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deletePayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'editOrderItems' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(OrderItem)], [], []),
  'editPayment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAdminRole' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAdminStatus' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllCustomerOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
  'getAllCustomerPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], []),
  'getAllCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], []),
  'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
  'getAllPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], []),
  'getAllProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getAllRiderAssignments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RiderAssignment)],
      [],
    ),
  'getAllRiderProfiles' : IDL.Func([IDL.Text], [IDL.Vec(RiderProfile)], []),
  'getAllSubUsers' : IDL.Func([IDL.Text], [IDL.Vec(SubUser)], []),
  'getCompanyProfile' : IDL.Func([], [CompanyProfile], ['query']),
  'getCompanyStatement' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [IDL.Vec(StatementEntry)],
      [],
    ),
  'getCustomer' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'storeNumber' : IDL.Text,
            'gstNumber' : IDL.Opt(IDL.Text),
            'address' : IDL.Text,
            'companyName' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getCustomerStatement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Int],
      [IDL.Vec(StatementEntry)],
      [],
    ),
  'getMyStatement' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [IDL.Vec(StatementEntry)],
      [],
    ),
  'getOrdersByStore' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Order)], []),
  'getOrdersForRider' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Order)], []),
  'getPaymentsByStore' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Payment)], []),
  'getRiderAssignment' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(RiderAssignment)],
      [],
    ),
  'getRiderProfile' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(RiderProfile)],
      [],
    ),
  'getWebhookUrl' : IDL.Func([IDL.Text], [IDL.Text], []),
  'markOrderDeliveredWithSignature' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
      [IDL.Text],
      [],
    ),
  'placeOrderV2' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(OrderItem),
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'replaceCustomers' : IDL.Func([IDL.Text, IDL.Vec(Customer)], [], []),
  'replaceProducts' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'replaceProductsWithDetails' : IDL.Func(
      [IDL.Text, IDL.Vec(ProductInput)],
      [],
      [],
    ),
  'saveRiderProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'setCompanyProfile' : IDL.Func([IDL.Text, CompanyProfile], [], []),
  'setWebhookUrl' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'subUserLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'subUserLoginV2' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'toggleProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'toggleSubUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateCustomer' : IDL.Func([IDL.Text, IDL.Text, Customer], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateOrderStatusRider' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProductImage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateProductRate' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Customer = IDL.Record({
    'storeNumber' : IDL.Text,
    'gstNumber' : IDL.Opt(IDL.Text),
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'accounts' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'rate' : IDL.Float64,
    'unit' : IDL.Text,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'rate' : IDL.Float64,
    'unit' : IDL.Text,
    'imageBase64' : IDL.Text,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'storeNumber' : IDL.Text,
    'gstNumber' : IDL.Opt(IDL.Text),
    'deleteReason' : IDL.Opt(IDL.Text),
    'orderId' : IDL.Text,
    'invoiceNumber' : IDL.Opt(IDL.Text),
    'deliverySignature' : IDL.Opt(IDL.Text),
    'totalAmount' : IDL.Float64,
    'address' : IDL.Text,
    'timestamp' : Time,
    'companyName' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'poNumber' : IDL.Text,
  });
  const Payment = IDL.Record({
    'deleted' : IDL.Bool,
    'paymentMethod' : IDL.Text,
    'paymentAdviceImage' : IDL.Text,
    'storeNumber' : IDL.Text,
    'deleteReason' : IDL.Opt(IDL.Text),
    'utrDetails' : IDL.Opt(IDL.Text),
    'paymentId' : IDL.Text,
    'timestamp' : Time,
    'companyName' : IDL.Text,
    'amount' : IDL.Float64,
    'chequeDetails' : IDL.Opt(IDL.Text),
  });
  const RiderAssignment = IDL.Record({
    'orderId' : IDL.Text,
    'riderEmail' : IDL.Text,
    'riderPhone' : IDL.Text,
    'riderName' : IDL.Text,
  });
  const RiderProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubUser = IDL.Record({
    'roleText' : IDL.Text,
    'active' : IDL.Bool,
    'password' : IDL.Text,
    'email' : IDL.Text,
  });
  const CompanyProfile = IDL.Record({
    'logoBase64' : IDL.Text,
    'gstNumber' : IDL.Text,
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const StatementEntry = IDL.Record({
    'entryDate' : Time,
    'entryType' : IDL.Text,
    'referenceNumber' : IDL.Text,
    'storeNumber' : IDL.Text,
    'credit' : IDL.Float64,
    'companyName' : IDL.Text,
    'debit' : IDL.Float64,
  });
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'rate' : IDL.Float64,
    'unit' : IDL.Text,
    'imageBase64' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func([IDL.Text, Customer], [], []),
    'addPayment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'assignRider' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'changeSubUserPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createSubUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
    'createSubUserWithPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'customerLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deletePayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'editOrderItems' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
        [],
        [],
      ),
    'editPayment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAdminRole' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAdminStatus' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllCustomerOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
    'getAllCustomerPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], []),
    'getAllCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], []),
    'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
    'getAllPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], []),
    'getAllProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getAllRiderAssignments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RiderAssignment)],
        [],
      ),
    'getAllRiderProfiles' : IDL.Func([IDL.Text], [IDL.Vec(RiderProfile)], []),
    'getAllSubUsers' : IDL.Func([IDL.Text], [IDL.Vec(SubUser)], []),
    'getCompanyProfile' : IDL.Func([], [CompanyProfile], ['query']),
    'getCompanyStatement' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [IDL.Vec(StatementEntry)],
        [],
      ),
    'getCustomer' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'storeNumber' : IDL.Text,
              'gstNumber' : IDL.Opt(IDL.Text),
              'address' : IDL.Text,
              'companyName' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getCustomerStatement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Int],
        [IDL.Vec(StatementEntry)],
        [],
      ),
    'getMyStatement' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [IDL.Vec(StatementEntry)],
        [],
      ),
    'getOrdersByStore' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Order)], []),
    'getOrdersForRider' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Order)], []),
    'getPaymentsByStore' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Payment)],
        [],
      ),
    'getRiderAssignment' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(RiderAssignment)],
        [],
      ),
    'getRiderProfile' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(RiderProfile)],
        [],
      ),
    'getWebhookUrl' : IDL.Func([IDL.Text], [IDL.Text], []),
    'markOrderDeliveredWithSignature' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
        [IDL.Text],
        [],
      ),
    'placeOrderV2' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(OrderItem),
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'replaceCustomers' : IDL.Func([IDL.Text, IDL.Vec(Customer)], [], []),
    'replaceProducts' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'replaceProductsWithDetails' : IDL.Func(
        [IDL.Text, IDL.Vec(ProductInput)],
        [],
        [],
      ),
    'saveRiderProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'setCompanyProfile' : IDL.Func([IDL.Text, CompanyProfile], [], []),
    'setWebhookUrl' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'subUserLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'subUserLoginV2' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'toggleProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'toggleSubUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateCustomer' : IDL.Func([IDL.Text, IDL.Text, Customer], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateOrderStatusRider' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProductImage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateProductRate' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };