/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanyProfile {
  'logoBase64' : string,
  'gstNumber' : string,
  'address' : string,
  'contactEmail' : string,
  'contactPhone' : string,
}
export interface Customer {
  'active' : boolean,
  'storeNumber' : string,
  'gstNumber' : [] | [string],
  'password' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'companyName' : string,
  'phone' : string,
}
export interface CustomerInput {
  'storeNumber' : string,
  'gstNumber' : [] | [string],
  'password' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'companyName' : string,
  'phone' : string,
}
export interface Order {
  'status' : string,
  'paymentMethod' : string,
  'deliverySignedAt' : [] | [Time],
  'storeNumber' : string,
  'gstNumber' : [] | [string],
  'deleteReason' : [] | [string],
  'orderId' : string,
  'deliveryStartTime' : [] | [Time],
  'invoiceNumber' : [] | [string],
  'deliverySignature' : [] | [string],
  'totalAmount' : number,
  'address' : string,
  'deliveryEndTime' : [] | [Time],
  'timestamp' : Time,
  'companyName' : string,
  'items' : Array<OrderItem>,
  'poNumber' : string,
}
export interface OrderItem {
  'qty' : bigint,
  'rate' : number,
  'unit' : string,
  'productId' : bigint,
  'productName' : string,
}
export interface Payment {
  'deleted' : boolean,
  'paymentMethod' : string,
  'paymentAdviceImage' : string,
  'storeNumber' : string,
  'deleteReason' : [] | [string],
  'utrDetails' : [] | [string],
  'paymentId' : string,
  'timestamp' : Time,
  'companyName' : string,
  'amount' : number,
  'chequeDetails' : [] | [string],
}
export interface Product {
  'id' : bigint,
  'active' : boolean,
  'name' : string,
  'rate' : number,
  'unit' : string,
  'imageBase64' : string,
}
export interface ProductInput {
  'name' : string,
  'rate' : number,
  'unit' : string,
  'imageBase64' : [] | [string],
}
export type Time = bigint;
export type UserRole = { 'manager' : null } |
  { 'admin' : null } |
  { 'accounts' : null };
export interface _SERVICE {
  'addCustomer' : ActorMethod<[string, CustomerInput], undefined>,
  'addCustomersOnly' : ActorMethod<[string, Array<CustomerInput>], undefined>,
  'addPayment' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      string,
      [] | [string],
      [] | [string],
      string,
    ],
    string
  >,
  'adminLogin' : ActorMethod<[string, string], string>,
  'changeAdminPassword' : ActorMethod<[string, string], undefined>,
  'createSubUser' : ActorMethod<[string, string, UserRole], undefined>,
  'customerLogin' : ActorMethod<[string, string], string>,
  'deleteCustomer' : ActorMethod<[string, string], undefined>,
  'editOrderItems' : ActorMethod<[string, string, Array<OrderItem>], undefined>,
  'editPayment' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      string,
      [] | [string],
      [] | [string],
      string,
    ],
    undefined
  >,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAllCustomers' : ActorMethod<[string], Array<Customer>>,
  'getAllOrders' : ActorMethod<[string], Array<Order>>,
  'getAllPayments' : ActorMethod<[string], Array<Payment>>,
  'getAllProducts' : ActorMethod<[string], Array<Product>>,
  'getAllProductsPublic' : ActorMethod<[], Array<Product>>,
  'getCompanyProfile' : ActorMethod<[], CompanyProfile>,
  'getCustomer' : ActorMethod<
    [string],
    [] | [
      {
        'storeNumber' : string,
        'gstNumber' : [] | [string],
        'address' : string,
        'companyName' : string,
      }
    ]
  >,
  'getOrdersByStore' : ActorMethod<[string, string], Array<Order>>,
  'getPaymentsByStore' : ActorMethod<[string, string], Array<Payment>>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, Array<OrderItem>],
    string
  >,
  'placeOrderV2' : ActorMethod<
    [string, string, string, string, [] | [string], Array<OrderItem>, string],
    string
  >,
  'replaceCustomers' : ActorMethod<[string, Array<CustomerInput>], undefined>,
  'replaceProducts' : ActorMethod<[string, Array<string>], undefined>,
  'replaceProductsWithDetails' : ActorMethod<
    [string, Array<ProductInput>],
    Array<Product>
  >,
  'setAllProductsActive' : ActorMethod<[string, boolean], undefined>,
  'setCompanyProfile' : ActorMethod<[string, CompanyProfile], undefined>,
  'softDeletePayment' : ActorMethod<[string, string, string], undefined>,
  'subUserLogin' : ActorMethod<[string, string], string>,
  'toggleCustomerActive' : ActorMethod<[string, string], undefined>,
  'toggleProduct' : ActorMethod<[string, bigint], undefined>,
  'updateCustomer' : ActorMethod<[string, string, CustomerInput], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string, string], undefined>,
  'updateProductImage' : ActorMethod<[string, bigint, string], undefined>,
  'updateProductRate' : ActorMethod<[string, bigint, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];