/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerInput = IDL.Record({
  'storeNumber' : IDL.Text,
  'gstNumber' : IDL.Opt(IDL.Text),
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'accounts' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'rate' : IDL.Float64,
  'unit' : IDL.Text,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'rate' : IDL.Float64,
  'unit' : IDL.Text,
  'imageBase64' : IDL.Text,
});
export const Customer = IDL.Record({
  'active' : IDL.Bool,
  'storeNumber' : IDL.Text,
  'gstNumber' : IDL.Opt(IDL.Text),
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'deliverySignedAt' : IDL.Opt(Time),
  'storeNumber' : IDL.Text,
  'gstNumber' : IDL.Opt(IDL.Text),
  'deleteReason' : IDL.Opt(IDL.Text),
  'orderId' : IDL.Text,
  'deliveryStartTime' : IDL.Opt(Time),
  'invoiceNumber' : IDL.Opt(IDL.Text),
  'deliverySignature' : IDL.Opt(IDL.Text),
  'totalAmount' : IDL.Float64,
  'address' : IDL.Text,
  'deliveryEndTime' : IDL.Opt(Time),
  'timestamp' : Time,
  'companyName' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'poNumber' : IDL.Text,
});
export const Payment = IDL.Record({
  'deleted' : IDL.Bool,
  'paymentMethod' : IDL.Text,
  'paymentAdviceImage' : IDL.Text,
  'storeNumber' : IDL.Text,
  'deleteReason' : IDL.Opt(IDL.Text),
  'utrDetails' : IDL.Opt(IDL.Text),
  'paymentId' : IDL.Text,
  'timestamp' : Time,
  'companyName' : IDL.Text,
  'amount' : IDL.Float64,
  'chequeDetails' : IDL.Opt(IDL.Text),
});
export const CompanyProfile = IDL.Record({
  'logoBase64' : IDL.Text,
  'gstNumber' : IDL.Text,
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'rate' : IDL.Float64,
  'unit' : IDL.Text,
  'imageBase64' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([IDL.Text, CustomerInput], [], []),
  'addCustomersOnly' : IDL.Func([IDL.Text, IDL.Vec(CustomerInput)], [], []),
  'addPayment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createSubUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  'customerLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'editOrderItems' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(OrderItem)], [], []),
  'editPayment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], []),
  'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
  'getAllPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], []),
  'getAllProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getAllProductsPublic' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCompanyProfile' : IDL.Func([], [CompanyProfile], ['query']),
  'getCustomer' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'storeNumber' : IDL.Text,
            'gstNumber' : IDL.Opt(IDL.Text),
            'address' : IDL.Text,
            'companyName' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getOrdersByStore' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Order)], []),
  'getPaymentsByStore' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Payment)], []),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
      [IDL.Text],
      [],
    ),
  'placeOrderV2' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(OrderItem),
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'replaceCustomers' : IDL.Func([IDL.Text, IDL.Vec(CustomerInput)], [], []),
  'replaceProducts' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'replaceProductsWithDetails' : IDL.Func(
      [IDL.Text, IDL.Vec(ProductInput)],
      [IDL.Vec(Product)],
      [],
    ),
  'setAllProductsActive' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setCompanyProfile' : IDL.Func([IDL.Text, CompanyProfile], [], []),
  'softDeletePayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'subUserLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'toggleCustomerActive' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'toggleProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateCustomer' : IDL.Func([IDL.Text, IDL.Text, CustomerInput], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProductImage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateProductRate' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [], []),
    'deleteOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignInvoiceNumber' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'markOrderDeliveredWithSignature' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllSubUsers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'id': IDL.Text, 'email': IDL.Text, 'role': IDL.Text, 'active': IDL.Bool, 'name': IDL.Opt(IDL.Text), 'phone': IDL.Opt(IDL.Text)}))], []),
    'createSubUserWithPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)], [], []),
    'toggleSubUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'changeSubUserPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignRider' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllRiderAssignments' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'orderId': IDL.Text, 'riderEmail': IDL.Text, 'riderName': IDL.Text, 'riderPhone': IDL.Text, 'assignedAt': IDL.Int}))], []),
    'saveRiderProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllRiderProfiles' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'email': IDL.Text, 'name': IDL.Text, 'phone': IDL.Text}))], []),
    'getOrdersForRider' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(IDL.Record({'orderId': IDL.Text, 'storeNumber': IDL.Text, 'companyName': IDL.Text, 'items': IDL.Vec(IDL.Record({'productId': IDL.Nat, 'productName': IDL.Text, 'qty': IDL.Nat, 'rate': IDL.Float64, 'unit': IDL.Text})), 'status': IDL.Text, 'createdAt': IDL.Int, 'updatedAt': IDL.Int, 'invoiceNumber': IDL.Opt(IDL.Text), 'totalAmount': IDL.Float64, 'notes': IDL.Opt(IDL.Text), 'deliveryAddress': IDL.Opt(IDL.Text), 'customerPhone': IDL.Opt(IDL.Text)}))], []),
    'updateOrderStatusRider' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text], [IDL.Text], []),
    'deletePayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getCustomerStatement' : IDL.Func([IDL.Text, IDL.Text, IDL.Int, IDL.Int], [IDL.Vec(IDL.Record({'date': IDL.Int, 'description': IDL.Text, 'debit': IDL.Float64, 'credit': IDL.Float64, 'balance': IDL.Float64, 'reference': IDL.Opt(IDL.Text), 'entryType': IDL.Text}))], []),
    'getCompanyStatement' : IDL.Func([IDL.Text, IDL.Int, IDL.Int], [IDL.Vec(IDL.Record({'date': IDL.Int, 'description': IDL.Text, 'debit': IDL.Float64, 'credit': IDL.Float64, 'balance': IDL.Float64, 'reference': IDL.Opt(IDL.Text), 'entryType': IDL.Text}))], []),
    'getMyStatement' : IDL.Func([IDL.Text, IDL.Int, IDL.Int], [IDL.Vec(IDL.Record({'date': IDL.Int, 'description': IDL.Text, 'debit': IDL.Float64, 'credit': IDL.Float64, 'balance': IDL.Float64, 'reference': IDL.Opt(IDL.Text), 'entryType': IDL.Text}))], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerInput = IDL.Record({
    'storeNumber' : IDL.Text,
    'gstNumber' : IDL.Opt(IDL.Text),
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'accounts' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'rate' : IDL.Float64,
    'unit' : IDL.Text,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'rate' : IDL.Float64,
    'unit' : IDL.Text,
    'imageBase64' : IDL.Text,
  });
  const Customer = IDL.Record({
    'active' : IDL.Bool,
    'storeNumber' : IDL.Text,
    'gstNumber' : IDL.Opt(IDL.Text),
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'deliverySignedAt' : IDL.Opt(Time),
    'storeNumber' : IDL.Text,
    'gstNumber' : IDL.Opt(IDL.Text),
    'deleteReason' : IDL.Opt(IDL.Text),
    'orderId' : IDL.Text,
    'deliveryStartTime' : IDL.Opt(Time),
    'invoiceNumber' : IDL.Opt(IDL.Text),
    'deliverySignature' : IDL.Opt(IDL.Text),
    'totalAmount' : IDL.Float64,
    'address' : IDL.Text,
    'deliveryEndTime' : IDL.Opt(Time),
    'timestamp' : Time,
    'companyName' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'poNumber' : IDL.Text,
  });
  const Payment = IDL.Record({
    'deleted' : IDL.Bool,
    'paymentMethod' : IDL.Text,
    'paymentAdviceImage' : IDL.Text,
    'storeNumber' : IDL.Text,
    'deleteReason' : IDL.Opt(IDL.Text),
    'utrDetails' : IDL.Opt(IDL.Text),
    'paymentId' : IDL.Text,
    'timestamp' : Time,
    'companyName' : IDL.Text,
    'amount' : IDL.Float64,
    'chequeDetails' : IDL.Opt(IDL.Text),
  });
  const CompanyProfile = IDL.Record({
    'logoBase64' : IDL.Text,
    'gstNumber' : IDL.Text,
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'rate' : IDL.Float64,
    'unit' : IDL.Text,
    'imageBase64' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func([IDL.Text, CustomerInput], [], []),
    'addCustomersOnly' : IDL.Func([IDL.Text, IDL.Vec(CustomerInput)], [], []),
    'addPayment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createSubUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
    'customerLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'editOrderItems' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
        [],
        [],
      ),
    'editPayment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], []),
    'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
    'getAllPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], []),
    'getAllProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getAllProductsPublic' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCompanyProfile' : IDL.Func([], [CompanyProfile], ['query']),
    'getCustomer' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'storeNumber' : IDL.Text,
              'gstNumber' : IDL.Opt(IDL.Text),
              'address' : IDL.Text,
              'companyName' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getOrdersByStore' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Order)], []),
    'getPaymentsByStore' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Payment)],
        [],
      ),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
        [IDL.Text],
        [],
      ),
    'placeOrderV2' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(OrderItem),
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'replaceCustomers' : IDL.Func([IDL.Text, IDL.Vec(CustomerInput)], [], []),
    'replaceProducts' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'replaceProductsWithDetails' : IDL.Func(
        [IDL.Text, IDL.Vec(ProductInput)],
        [IDL.Vec(Product)],
        [],
      ),
    'setAllProductsActive' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setCompanyProfile' : IDL.Func([IDL.Text, CompanyProfile], [], []),
    'softDeletePayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'subUserLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'toggleCustomerActive' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'toggleProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateCustomer' : IDL.Func([IDL.Text, IDL.Text, CustomerInput], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProductImage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateProductRate' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [], []),
    'deleteOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignInvoiceNumber' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'markOrderDeliveredWithSignature' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllSubUsers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'id': IDL.Text, 'email': IDL.Text, 'role': IDL.Text, 'active': IDL.Bool, 'name': IDL.Opt(IDL.Text), 'phone': IDL.Opt(IDL.Text)}))], []),
    'createSubUserWithPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)], [], []),
    'toggleSubUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'changeSubUserPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignRider' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllRiderAssignments' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'orderId': IDL.Text, 'riderEmail': IDL.Text, 'riderName': IDL.Text, 'riderPhone': IDL.Text, 'assignedAt': IDL.Int}))], []),
    'saveRiderProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllRiderProfiles' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'email': IDL.Text, 'name': IDL.Text, 'phone': IDL.Text}))], []),
    'getOrdersForRider' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(IDL.Record({'orderId': IDL.Text, 'storeNumber': IDL.Text, 'companyName': IDL.Text, 'items': IDL.Vec(IDL.Record({'productId': IDL.Nat, 'productName': IDL.Text, 'qty': IDL.Nat, 'rate': IDL.Float64, 'unit': IDL.Text})), 'status': IDL.Text, 'createdAt': IDL.Int, 'updatedAt': IDL.Int, 'invoiceNumber': IDL.Opt(IDL.Text), 'totalAmount': IDL.Float64, 'notes': IDL.Opt(IDL.Text), 'deliveryAddress': IDL.Opt(IDL.Text), 'customerPhone': IDL.Opt(IDL.Text)}))], []),
    'updateOrderStatusRider' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text], [IDL.Text], []),
    'deletePayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getCustomerStatement' : IDL.Func([IDL.Text, IDL.Text, IDL.Int, IDL.Int], [IDL.Vec(IDL.Record({'date': IDL.Int, 'description': IDL.Text, 'debit': IDL.Float64, 'credit': IDL.Float64, 'balance': IDL.Float64, 'reference': IDL.Opt(IDL.Text), 'entryType': IDL.Text}))], []),
    'getCompanyStatement' : IDL.Func([IDL.Text, IDL.Int, IDL.Int], [IDL.Vec(IDL.Record({'date': IDL.Int, 'description': IDL.Text, 'debit': IDL.Float64, 'credit': IDL.Float64, 'balance': IDL.Float64, 'reference': IDL.Opt(IDL.Text), 'entryType': IDL.Text}))], []),
    'getMyStatement' : IDL.Func([IDL.Text, IDL.Int, IDL.Int], [IDL.Vec(IDL.Record({'date': IDL.Int, 'description': IDL.Text, 'debit': IDL.Float64, 'credit': IDL.Float64, 'balance': IDL.Float64, 'reference': IDL.Opt(IDL.Text), 'entryType': IDL.Text}))], []),
  });
};

export const init = ({ IDL }) => { return []; };