/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Customer {
    active: boolean;
    storeNumber: string;
    gstNumber?: string;
    password: string;
    name: string;
    email: string;
    address: string;
    companyName: string;
    phone: string;
}
export interface ProductInput {
    name: string;
    rate: number;
    unit: string;
    imageBase64?: string;
}
export interface CompanyProfile {
    logoBase64: string;
    gstNumber: string;
    address: string;
    contactEmail: string;
    contactPhone: string;
}
export type Time = bigint;
export interface OrderItem {
    qty: bigint;
    rate: number;
    unit: string;
    productId: bigint;
    productName: string;
}
export interface Payment {
    deleted: boolean;
    paymentMethod: string;
    paymentAdviceImage: string;
    storeNumber: string;
    deleteReason?: string;
    utrDetails?: string;
    paymentId: string;
    timestamp: Time;
    companyName: string;
    amount: number;
    chequeDetails?: string;
}
export interface Order {
    status: string;
    paymentMethod: string;
    deliverySignedAt?: Time;
    storeNumber: string;
    gstNumber?: string;
    deleteReason?: string;
    orderId: string;
    deliveryStartTime?: Time;
    invoiceNumber?: string;
    deliverySignature?: string;
    totalAmount: number;
    address: string;
    deliveryEndTime?: Time;
    timestamp: Time;
    companyName: string;
    items: Array<OrderItem>;
    poNumber: string;
}
export interface Product {
    id: bigint;
    active: boolean;
    name: string;
    rate: number;
    unit: string;
    imageBase64: string;
}
export interface CustomerInput {
    storeNumber: string;
    gstNumber?: string;
    password: string;
    name: string;
    email: string;
    address: string;
    companyName: string;
    phone: string;
}
export enum UserRole {
    manager = "manager",
    admin = "admin",
    accounts = "accounts"
}
export interface backendInterface {
    addCustomer(token: string, newCustomer: CustomerInput): Promise<void>;
    addCustomersOnly(token: string, customerList: Array<CustomerInput>): Promise<void>;
    addPayment(token: string, storeNumber: string, companyName: string, amount: number, paymentMethod: string, chequeDetails: string | null, utrDetails: string | null, paymentAdviceImage: string): Promise<string>;
    adminLogin(email: string, password: string): Promise<string>;
    changeAdminPassword(token: string, newPassword: string): Promise<void>;
    createSubUser(token: string, email: string, role: UserRole): Promise<void>;
    customerLogin(storeNumber: string, password: string): Promise<string>;
    deleteCustomer(token: string, storeNumber: string): Promise<void>;
    editOrderItems(token: string, orderId: string, newItems: Array<OrderItem>): Promise<void>;
    editPayment(token: string, paymentId: string, storeNumber: string, companyName: string, amount: number, paymentMethod: string, chequeDetails: string | null, utrDetails: string | null, paymentAdviceImage: string): Promise<void>;
    getActiveProducts(): Promise<Array<Product>>;
    getAllCustomers(token: string): Promise<Array<Customer>>;
    getAllOrders(token: string): Promise<Array<Order>>;
    getAllPayments(token: string): Promise<Array<Payment>>;
    getAllProducts(_token: string): Promise<Array<Product>>;
    getAllProductsPublic(): Promise<Array<Product>>;
    getCompanyProfile(): Promise<CompanyProfile>;
    getCustomer(storeNumber: string): Promise<{
        storeNumber: string;
        gstNumber?: string;
        address: string;
        companyName: string;
    } | null>;
    getOrdersByStore(token: string, storeNumber: string): Promise<Array<Order>>;
    getPaymentsByStore(token: string, storeNumber: string): Promise<Array<Payment>>;
    placeOrder(token: string, storeNumber: string, companyName: string, address: string, items: Array<OrderItem>): Promise<string>;
    placeOrderV2(token: string, storeNumber: string, companyName: string, address: string, gstNumber: string | null, items: Array<OrderItem>, paymentMethod: string): Promise<string>;
    replaceCustomers(token: string, customerList: Array<CustomerInput>): Promise<void>;
    replaceProducts(token: string, productNames: Array<string>): Promise<void>;
    replaceProductsWithDetails(token: string, items: Array<ProductInput>): Promise<Array<Product>>;
    setAllProductsActive(token: string, active: boolean): Promise<void>;
    setCompanyProfile(token: string, profile: CompanyProfile): Promise<void>;
    softDeletePayment(token: string, paymentId: string, reason: string): Promise<void>;
    subUserLogin(email: string, _password: string): Promise<string>;
    toggleCustomerActive(token: string, storeNumber: string): Promise<void>;
    toggleProduct(token: string, productId: bigint): Promise<void>;
    updateCustomer(token: string, storeNumber: string, updatedCustomer: CustomerInput): Promise<void>;
    updateOrderStatus(token: string, orderId: string, status: string): Promise<void>;
    updateProductImage(token: string, productId: bigint, imageBase64: string): Promise<void>;
    updateProductRate(token: string, productId: bigint, newRate: number): Promise<void>;
}
import type { Customer as _Customer, CustomerInput as _CustomerInput, Order as _Order, OrderItem as _OrderItem, Payment as _Payment, ProductInput as _ProductInput, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCustomer(arg0: string, arg1: CustomerInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, to_candid_CustomerInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, to_candid_CustomerInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addCustomersOnly(arg0: string, arg1: Array<CustomerInput>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomersOnly(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomersOnly(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addPayment(arg0: string, arg1: string, arg2: string, arg3: number, arg4: string, arg5: string | null, arg6: string | null, arg7: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async changeAdminPassword(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminPassword(arg0, arg1);
            return result;
        }
    }
    async createSubUser(arg0: string, arg1: string, arg2: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubUser(arg0, arg1, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubUser(arg0, arg1, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async customerLogin(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.customerLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.customerLogin(arg0, arg1);
            return result;
        }
    }
    async assignInvoiceNumber(arg0: string, arg1: string): Promise<string> {
        const isMethodNotFound = (e: unknown) => {
            const msg = e instanceof Error ? e.message : String(e);
            return msg.includes('has no update method') || msg.includes('IC0536') || msg.includes('assignInvoiceNumber');
        };
        try {
            const result = await this.actor.assignInvoiceNumber(arg0, arg1);
            return result;
        } catch (e) {
            if (isMethodNotFound(e)) {
                // Fallback: updateOrderStatus triggers auto-invoice assignment in backend
                try {
                    await this.actor.updateOrderStatus(arg0, arg1, 'delivered');
                    return 'INV-A1VS-??';
                } catch (e2) {
                    const msg = e2 instanceof Error ? e2.message : 'Failed to assign invoice number';
                    throw new Error(msg);
                }
            }
            if (this.processError) { this.processError(e); throw new Error("unreachable"); }
            throw e;
        }
    }
    async deleteOrder(arg0: string, arg1: string, arg2: string): Promise<void> {
        const isMethodNotFound = (e: unknown) => {
            const msg = e instanceof Error ? e.message : String(e);
            return msg.includes('has no update method') || msg.includes('IC0536') || msg.includes('deleteOrder');
        };
        try {
            await this.actor.deleteOrder(arg0, arg1, arg2);
        } catch (e) {
            if (isMethodNotFound(e)) {
                // Fallback: mark order as deleted via updateOrderStatus
                try {
                    await this.actor.updateOrderStatus(arg0, arg1, 'deleted');
                    return;
                } catch (e2) {
                    const msg = e2 instanceof Error ? e2.message : 'Failed to delete order';
                    throw new Error(msg);
                }
            }
            if (this.processError) { this.processError(e); throw new Error("unreachable"); }
            throw e;
        }
    }
    async deleteCustomer(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0, arg1);
            return result;
        }
    }
    async editOrderItems(arg0: string, arg1: string, arg2: Array<OrderItem>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editOrderItems(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editOrderItems(arg0, arg1, arg2);
            return result;
        }
    }
    async editPayment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: string, arg6: string | null, arg7: string | null, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editPayment(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg7), arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPayment(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg7), arg8);
            return result;
        }
    }
    async getActiveProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveProducts();
            return result;
        }
    }
    async getAllCustomers(arg0: string): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPayments(arg0: string): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts(arg0);
            return result;
        }
    }
    async getAllProductsPublic(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductsPublic();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductsPublic();
            return result;
        }
    }
    async getCompanyProfile(): Promise<CompanyProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyProfile();
            return result;
        }
    }
    async getCustomer(arg0: string): Promise<{
        storeNumber: string;
        gstNumber?: string;
        address: string;
        companyName: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByStore(arg0: string, arg1: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStore(arg0, arg1);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStore(arg0, arg1);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentsByStore(arg0: string, arg1: string): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByStore(arg0, arg1);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByStore(arg0, arg1);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<OrderItem>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async placeOrderV2(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: Array<OrderItem>, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrderV2(arg0, arg1, arg2, arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrderV2(arg0, arg1, arg2, arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async replaceCustomers(arg0: string, arg1: Array<CustomerInput>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replaceCustomers(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replaceCustomers(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async replaceProducts(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replaceProducts(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replaceProducts(arg0, arg1);
            return result;
        }
    }
    async replaceProductsWithDetails(arg0: string, arg1: Array<ProductInput>): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.replaceProductsWithDetails(arg0, to_candid_vec_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replaceProductsWithDetails(arg0, to_candid_vec_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setAllProductsActive(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAllProductsActive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAllProductsActive(arg0, arg1);
            return result;
        }
    }
    async setCompanyProfile(arg0: string, arg1: CompanyProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCompanyProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCompanyProfile(arg0, arg1);
            return result;
        }
    }
    async softDeletePayment(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.softDeletePayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.softDeletePayment(arg0, arg1, arg2);
            return result;
        }
    }
    async subUserLogin(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.subUserLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subUserLogin(arg0, arg1);
            return result;
        }
    }
    async toggleCustomerActive(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCustomerActive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCustomerActive(arg0, arg1);
            return result;
        }
    }
    async toggleProduct(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleProduct(arg0, arg1);
            return result;
        }
    }
    async updateCustomer(arg0: string, arg1: string, arg2: CustomerInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1, to_candid_CustomerInput_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1, to_candid_CustomerInput_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProductImage(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductImage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductImage(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProductRate(arg0: string, arg1: bigint, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductRate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductRate(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Customer_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        storeNumber: string;
        gstNumber: [] | [string];
        address: string;
        companyName: string;
    }]): {
    storeNumber: string;
    gstNumber?: string;
    address: string;
    companyName: string;
} | null {
    return value.length === 0 ? null : from_candid_record_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    paymentMethod: string;
    deliverySignedAt: [] | [_Time];
    storeNumber: string;
    gstNumber: [] | [string];
    deleteReason: [] | [string];
    orderId: string;
    deliveryStartTime: [] | [_Time];
    invoiceNumber: [] | [string];
    deliverySignature: [] | [string];
    totalAmount: number;
    address: string;
    deliveryEndTime: [] | [_Time];
    timestamp: _Time;
    companyName: string;
    items: Array<_OrderItem>;
    poNumber: string;
}): {
    status: string;
    paymentMethod: string;
    deliverySignedAt?: Time;
    storeNumber: string;
    gstNumber?: string;
    deleteReason?: string;
    orderId: string;
    deliveryStartTime?: Time;
    invoiceNumber?: string;
    deliverySignature?: string;
    totalAmount: number;
    address: string;
    deliveryEndTime?: Time;
    timestamp: Time;
    companyName: string;
    items: Array<OrderItem>;
    poNumber: string;
} {
    return {
        status: value.status,
        paymentMethod: value.paymentMethod,
        deliverySignedAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.deliverySignedAt)),
        storeNumber: value.storeNumber,
        gstNumber: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.gstNumber)),
        deleteReason: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.deleteReason)),
        orderId: value.orderId,
        deliveryStartTime: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.deliveryStartTime)),
        invoiceNumber: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.invoiceNumber)),
        deliverySignature: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.deliverySignature)),
        totalAmount: value.totalAmount,
        address: value.address,
        deliveryEndTime: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.deliveryEndTime)),
        timestamp: value.timestamp,
        companyName: value.companyName,
        items: value.items,
        poNumber: value.poNumber
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deleted: boolean;
    paymentMethod: string;
    paymentAdviceImage: string;
    storeNumber: string;
    deleteReason: [] | [string];
    utrDetails: [] | [string];
    paymentId: string;
    timestamp: _Time;
    companyName: string;
    amount: number;
    chequeDetails: [] | [string];
}): {
    deleted: boolean;
    paymentMethod: string;
    paymentAdviceImage: string;
    storeNumber: string;
    deleteReason?: string;
    utrDetails?: string;
    paymentId: string;
    timestamp: Time;
    companyName: string;
    amount: number;
    chequeDetails?: string;
} {
    return {
        deleted: value.deleted,
        paymentMethod: value.paymentMethod,
        paymentAdviceImage: value.paymentAdviceImage,
        storeNumber: value.storeNumber,
        deleteReason: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.deleteReason)),
        utrDetails: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.utrDetails)),
        paymentId: value.paymentId,
        timestamp: value.timestamp,
        companyName: value.companyName,
        amount: value.amount,
        chequeDetails: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.chequeDetails))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    storeNumber: string;
    gstNumber: [] | [string];
    address: string;
    companyName: string;
}): {
    storeNumber: string;
    gstNumber?: string;
    address: string;
    companyName: string;
} {
    return {
        storeNumber: value.storeNumber,
        gstNumber: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.gstNumber)),
        address: value.address,
        companyName: value.companyName
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    storeNumber: string;
    gstNumber: [] | [string];
    password: string;
    name: string;
    email: string;
    address: string;
    companyName: string;
    phone: string;
}): {
    active: boolean;
    storeNumber: string;
    gstNumber?: string;
    password: string;
    name: string;
    email: string;
    address: string;
    companyName: string;
    phone: string;
} {
    return {
        active: value.active,
        storeNumber: value.storeNumber,
        gstNumber: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.gstNumber)),
        password: value.password,
        name: value.name,
        email: value.email,
        address: value.address,
        companyName: value.companyName,
        phone: value.phone
    };
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CustomerInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerInput): _CustomerInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ProductInput_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): _ProductInput {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    storeNumber: string;
    gstNumber?: string;
    password: string;
    name: string;
    email: string;
    address: string;
    companyName: string;
    phone: string;
}): {
    storeNumber: string;
    gstNumber: [] | [string];
    password: string;
    name: string;
    email: string;
    address: string;
    companyName: string;
    phone: string;
} {
    return {
        storeNumber: value.storeNumber,
        gstNumber: value.gstNumber ? candid_some(value.gstNumber) : candid_none(),
        password: value.password,
        name: value.name,
        email: value.email,
        address: value.address,
        companyName: value.companyName,
        phone: value.phone
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    rate: number;
    unit: string;
    imageBase64?: string;
}): {
    name: string;
    rate: number;
    unit: string;
    imageBase64: [] | [string];
} {
    return {
        name: value.name,
        rate: value.rate,
        unit: value.unit,
        imageBase64: value.imageBase64 ? candid_some(value.imageBase64) : candid_none()
    };
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    manager: null;
} | {
    admin: null;
} | {
    accounts: null;
} {
    return value == UserRole.manager ? {
        manager: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.accounts ? {
        accounts: null
    } : value;
}
function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ProductInput>): Array<_ProductInput> {
    return value.map((x)=>to_candid_ProductInput_n21(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CustomerInput>): Array<_CustomerInput> {
    return value.map((x)=>to_candid_CustomerInput_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
